apiVersion: v1
kind: Service
metadata:
  labels:
    app: gohttpserver
  name: gohttpserver
  namespace: httpserver-istio
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 81
  selector:
    app: gohttpserver
